### ISSUE TITLE
Add AMI Permission in FFM and IRL

### ISSUE THREAD

**Issue by apfeiffer85** [zalando-stups/sevenseconds#20]
Currently seven seconds set the AMI Permissions only in Frankfurt. But we also need AMI Permissions in Ireland

**Comment by hjacobs** [comment]
What AMI permissions are you referring to?

**Comment by tuxlife** [comment]
@apfeiffer85 i can't confirm this bug

sevenseconds searches in all regions in the config-yaml and add the permission, if no base ami found

**Comment by apfeiffer85** [comment]
Ok maybe i have to wait a bit longer until the Permissions are set .... will take a look at this again if i setup a new account. :-)
