### ISSUE TITLE
Can we adjust the process order

### ISSUE THREAD

**Issue by apfeiffer85** [zalando-stups/sevenseconds#21]
It would be nice to first create the SAML-Provider and IAM-Roles and after that the NAT and ODD hosts. 
Because in some cases seven seconds can't create the EC2 Instances if the Account isn't verified and than the process stops. 

Would be nice to have a working SAML login at this point.

**Comment by hjacobs** [comment]
I see no problem in changing the order as suggested by you

**Comment by tuxlife** [comment]
done in Release: https://github.com/zalando-stups/sevenseconds/tree/0.46
