### ISSUE TITLE
Even if a SSL certificate is not uploaded you get an ok

### ISSUE THREAD

**Issue by mawenzel** [zalando-stups/sevenseconds#22]
If you want to upload an SSL certificate and it does not work, then you get an OK from sevenseconds.

![could not upload ssl cert](https://cloud.githubusercontent.com/assets/11570974/8254272/4ecce5a6-1697-11e5-8a59-bf28f0486e59.png)

**Comment by tuxlife** [comment]
done in Release: https://github.com/zalando-stups/sevenseconds/tree/0.46
