### ISSUE TITLE
SSH Bastion instance runs in timeout

### ISSUE THREAD

**Issue by mawenzel** [zalando-stups/sevenseconds#23]
By running sevensecods at the step start bastion instance, it comes to timeouts by waiting for SSH port of ....

**Comment by tuxlife** [comment]
it is not a bug. is is a feature.

we can change the progress and switch this check or we shorten the time.

**Comment by apfeiffer85** [comment]
we should decrease the Timeout (maybe to 1-2Min) and we should also check how long the instance is running. And if the instance is still running an hour or so ( and it still gets a timeout ), than sevenseconds should restart the instance.

**Comment by tuxlife** [comment]
done in Release: https://github.com/zalando-stups/sevenseconds/tree/0.46
