### ISSUE TITLE
Consider setting up S3 VPC Endpoints for all accounts.

### ISSUE THREAD

**Issue by sarnowski** [zalando-stups/sevenseconds#31]
https://aws.amazon.com/blogs/aws/new-vpc-endpoint-for-amazon-s3/

**Comment by hjacobs** [comment]
Benefit: this would avoid going through NAT instances for S3 access (better performance? one less hop to go wrong..)

**Comment by apfeiffer85** [comment]
I've created one Endpoint in our Account and in another Account (Region: Ireland). 
And the speed and latency to S3 is much faster. 

Therefore "+1" for this issue. 

But i only enable this Endpoint for "internal" subnets.

**Comment by hjacobs** [comment]
:+1: for doing this soon

**Comment by tuxlife** [comment]
done with 6352f599e1b0ade376aee005483715ad91b5f4f8
