### ISSUE TITLE
Add Support for AWS-NAT-Gateways

### ISSUE THREAD

**Issue by apfeiffer85** [zalando-stups/sevenseconds#32]
AWS has now NAT-Gateways so basically NAT as a Service. ;-) 

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html

Migration from NAT-Instances to AWS-NAT-Gateway: 

http://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-nat-gateway.html#nat-instance-migrate

I guess we should test this and integrate this to our default Account setup. 
Currently NAT-Gateways are only available in eu-west-1 ( not in eu-central-1 ).

**Comment by hjacobs** [comment]
:+1: also might be slightly cheaper, but depends on GB transferred: http://aws.amazon.com/vpc/pricing/

**Comment by tuxlife** [comment]
done with 1112a70ddf86f2c8c7ec2de8c8d99df973117b17
