### ISSUE TITLE
Find latest version of "odd" Docker image automatically

### ISSUE THREAD

**Issue by hjacobs** [zalando-stups/sevenseconds#35]
Current version of "odd" in our Open Source Docker registry: registry.opensource.zalan.do/stups/odd:cd6

Seven Seconds should actually find the latest version from the Open Source Registry (via Pier One's REST API): https://registry.opensource.zalan.do/teams/stups/artifacts/odd/tags

**Comment by prayerslayer** [comment]
Does "latest" here mean something else than "youngest image regarding push time"? If not we can just use `registry.opensource.zalan.do/stups/odd:latest`.

**Comment by tuxlife** [comment]
@prayerslayer not for our opensource regitry :confounded:

**Comment by hjacobs** [comment]
@prayerslayer @tuxlife  `registry.opensource.zalan.do/stups/odd:latest` would not be audit compliant anyway (as we cannot track what version is running where), so you have to use the REST API to find the latest version...
